ALTER TABLE album
    ADD version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE artist
    ADD version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE genre
    ADD version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE song
    ADD version BIGINT NOT NULL DEFAULT 0;